import { UnknownPersonalityCodeError } from "./errors.js";

export const PERSONALITY_CATALOG = Object.freeze({
  HLTC: Object.freeze({
    code: "HLTC",
    name: "耄耋本耄",
    title: "暴躁橘猫王",
    dimensionCombo: "H（哈气型）+ L（持久型）+ T（高音型）+ C（混沌型）",
    themeColor: "#FF4500（橙红色）",
    emoji: "😾",
    rarityText: "★★★★★（极稀有，约3%用户）",
    rarityRateText: "约3%用户",
    coreDescription: "你就是耄耋转世。哈气又长又尖又乱，像一只闯入别人家的橘猫——不是你家的地盘你也要哈。你的哈气没有规律可言，纯粹是原始怒火的声学表达。",
    fullCopy: `🐱 **耄耋本耄 · 暴躁橘猫王**\n\n恭喜你，你触发了最稀有的人格类型——耄耋本耄。\n\n你的哈气数据简直是为"暴躁"而生的：响度拉满、持续时间超长、频率尖锐、而且完全没有规律。这四个维度同时达到极值的人，在统计学上属于"猫界核武器"级别。\n\n如果你的哈气有段位，你就是最强王者。如果哈气是一门武功，你就是独孤求败。如果哈气是一种货币，你就是印钞机。\n\n⚠️ 温馨提示：请勿在以下场合使用你的哈气技能——图书馆、考场、相亲现场、面试中。虽然你的哈气很有气势，但社会可能还没准备好接受它。\n\n🏆 **耄耋认证**：你的哈气已经获得了"耄耋本耄"官方认证。这是一份荣誉，也是一种警告。`,
    hissPortrait: Object.freeze({
      loudness: 10,
      pitch: 10,
      endurance: 10,
      chaos: 10,
      stability: 2,
      burst: 10,
    }),
    knownCat: "圆头耄耋（传说级暴躁橘猫）",
    socialTags: Object.freeze(["#暴躁", "#持久", "#尖锐", "#不可预测", "#耄耋认证"]),
  }),

  HLTR: Object.freeze({
    code: "HLTR",
    name: "喷射战士",
    title: "稳定输出机",
    dimensionCombo: "H（哈气型）+ L（持久型）+ T（高音型）+ R（节奏型）",
    themeColor: "#FF6347（番茄红）",
    emoji: "🔥",
    rarityText: "★★★★☆（稀有，约5%用户）",
    rarityRateText: "约5%用户",
    coreDescription: "你的哈气像高压水枪——持续、尖锐、方向稳定。别人哈气是情绪发泄，你哈气是定向打击。",
    fullCopy: `🔥 **喷射战士 · 稳定输出机**\n\n你的哈气有一个显著特点：稳。不是那种"偶尔厉害一下"的稳，而是"从头到尾都保持高强度"的稳。\n\n响度够大、频率够高、持续时间够长，而且——最可怕的——你的频率变化非常规律。这意味着你不是在乱哈，你是在**有节奏地**输出伤害。\n\n如果把哈气比作射击游戏，你就是那个压枪压得最稳的玩家。别人哈气是霰弹枪（范围大但精度低），你哈气是狙击枪（精准、持续、致命）。\n\n💡 建议：你可以尝试参加"最长稳定哈气"挑战赛，你的数据非常有竞争力。`,
    hissPortrait: Object.freeze({
      loudness: 10,
      pitch: 10,
      endurance: 10,
      chaos: 2,
      stability: 10,
      burst: 8,
    }),
    knownCat: "被抢罐头的英短（持续稳定抗议型）",
    socialTags: Object.freeze(["#稳定输出", "#高压水枪", "#持久战", "#技术流"]),
  }),

  HLFC: Object.freeze({
    code: "HLFC",
    name: "低音轰炸机",
    title: "震撼弹",
    dimensionCombo: "H（哈气型）+ L（持久型）+ F（低沉型）+ C（混沌型）",
    themeColor: "#8B0000（暗红色）",
    emoji: "💥",
    rarityText: "★★★★☆（稀有，约5%用户）",
    rarityRateText: "约5%用户",
    coreDescription: "你的哈气像地震前的低频预警——持续不断、低沉厚重、还带着不规则的震颤。",
    fullCopy: `💥 **低音轰炸机 · 震撼弹**\n\n你的哈气不走寻常路。别人追求尖锐刺耳，你选择低频轰炸。\n\n你的哈气主频偏低，这意味着声音不尖锐，但能量集中在低频段——就像地震波一样，虽然"听"起来不大，但能让人感受到物理震动。再加上你超长的持续时间和不规则的频率变化，你的哈气效果类似于"持续的低频炸弹"。\n\n对方可能听不清你在哈什么，但身体已经本能地后退了三步。这不是恐惧，这是生物本能——低频声音会触发哺乳动物的"危险预警"反应。\n\n🎵 你可能适合：配音低音角色、给恐怖电影做音效、或者去当地震预警系统。`,
    hissPortrait: Object.freeze({
      loudness: 10,
      pitch: 4,
      endurance: 10,
      chaos: 10,
      stability: 2,
      burst: 7,
    }),
    knownCat: "被逼洗澡的缅因猫（低频持续抗议型）",
    socialTags: Object.freeze(["#低音炮", "#震撼弹", "#持续轰炸", "#不可预测"]),
  }),

  HLFR: Object.freeze({
    code: "HLFR",
    name: "威慑之王",
    title: "终极Boss",
    dimensionCombo: "H（哈气型）+ L（持久型）+ F（低沉型）+ R（节奏型）",
    themeColor: "#4B0082（靛蓝色）",
    emoji: "👑",
    rarityText: "★★★★☆（稀有，约5%用户）",
    rarityRateText: "约5%用户",
    coreDescription: "你的哈气是教科书级别的威慑——稳定、低沉、持久。你不是在哈气，你是在宣战。",
    fullCopy: `👑 **威慑之王 · 终极Boss**\n\n如果哈气界有段位系统，你就是那个"看起来不怎么厉害但谁也打不过"的隐藏Boss。\n\n你的哈气数据组合非常特殊：响度大、持续时间长、频率低沉、而且极其稳定。这意味着你的哈气不是情绪化的爆发，而是**冷静的、持续的、有计划的威慑**。\n\n就像一只领地被侵犯的老虎——它不会像小猫一样乱叫，而是发出低沉的、持续的、稳定的警告。这种哈气的可怕之处在于：它传递的信息是"我很冷静，但我很认真"。\n\n在哈气PK中，遇到你的人往往会感到一种莫名的压迫感——不是恐惧，而是"这个对手不好惹"的直觉。\n\n🎯 你的哈气风格最适合：谈判桌上施压、给不听话的下属"开会"、以及在猫咖里镇场子。`,
    hissPortrait: Object.freeze({
      loudness: 10,
      pitch: 4,
      endurance: 10,
      chaos: 2,
      stability: 10,
      burst: 7,
    }),
    knownCat: "领地巡逻的缅因猫（冷静威慑型）",
    socialTags: Object.freeze(["#终极Boss", "#冷静威慑", "#低频压制", "#持久战之王"]),
  }),

  HPTC: Object.freeze({
    code: "HPTC",
    name: "闪电刺客",
    title: "暴击刺客",
    dimensionCombo: "H（哈气型）+ P（脉冲型）+ T（高音型）+ C（混沌型）",
    themeColor: "#FFD700（金色）",
    emoji: "⚡",
    rarityText: "★★★☆☆（较少见，约8%用户）",
    rarityRateText: "约8%用户",
    coreDescription: "你的哈气像闪电——快、准、狠、不可预测。你的战术是：打一枪换一个地方。",
    fullCopy: `⚡ **闪电刺客 · 暴击刺客**\n\n你的哈气风格可以用四个字概括：快准狠乱。\n\n响度大说明每一击都有伤害，时间短说明出手速度极快，频率高说明攻击穿透力强，混沌度高说明完全不可预测。这四个属性组合在一起，你就是哈气界的"刺客"——别人还没反应过来，你已经完成了一轮"哈完就跑"。\n\n你的哈气就像游戏里的暴击——平时不显山不露水，一旦出手就是致命一击。而且因为每次哈气的频率和节奏都不同，对手永远无法预判你的下一步。\n\n🗡️ 战术建议：在PK中，你的优势在于"出其不意"。不需要和持久型选手硬拼，用你的爆发力和不可预测性打乱对方的节奏。`,
    hissPortrait: Object.freeze({
      loudness: 10,
      pitch: 10,
      endurance: 4,
      chaos: 10,
      stability: 2,
      burst: 10,
    }),
    knownCat: "被突然吓到的暹罗猫（暴起反击型）",
    socialTags: Object.freeze(["#闪电战", "#暴击", "#不可预测", "#刺客"]),
  }),

  HPTR: Object.freeze({
    code: "HPTR",
    name: "机枪手",
    title: "连发射手",
    dimensionCombo: "H（哈气型）+ P（脉冲型）+ T（高音型）+ R（节奏型）",
    themeColor: "#DC143C（猩红色）",
    emoji: "🔫",
    rarityText: "★★★☆☆（较少见，约8%用户）",
    rarityRateText: "约8%用户",
    coreDescription: "你的哈气像机关枪——短促、尖锐、节奏稳定。哒哒哒哒，每一发都精准命中。",
    fullCopy: `🔫 **机枪手 · 连发射手**\n\n如果你的哈气有声音描述，那就是：哒哒哒哒哒。\n\n你是哈气界的"射速流"玩家——虽然每次哈气时间不长，但频率极高、节奏稳定、而且每一发的响度都不小。这意味着你在短时间内可以输出大量的"哈气伤害"。\n\n你的频率变化很有规律，说明你不是在乱哈——你是在**有节奏地**连射。就像一个训练有素的机枪手，每一发子弹都指向同一个方向。\n\n在PK中，你的DPS（每秒伤害输出）可能是所有人格中最高的。持久型选手可能总伤害更高，但你的瞬间爆发力无人能及。\n\n🎮 游戏类比：你就是MOBA游戏里的ADC——输出爆炸但身板脆，需要快速解决战斗。`,
    hissPortrait: Object.freeze({
      loudness: 10,
      pitch: 10,
      endurance: 4,
      chaos: 2,
      stability: 10,
      burst: 10,
    }),
    knownCat: "看到黄瓜后的英短（连续惊吓哈气型）",
    socialTags: Object.freeze(["#连射", "#DPS之王", "#节奏感", "#射速流"]),
  }),

  HPFC: Object.freeze({
    code: "HPFC",
    name: "混沌低音炮",
    title: "随机炸弹",
    dimensionCombo: "H（哈气型）+ P（脉冲型）+ F（低沉型）+ C（混沌型）",
    themeColor: "#9932CC（暗紫色）",
    emoji: "🎆",
    rarityText: "★★★☆☆（较少见，约7%用户）",
    rarityRateText: "约7%用户",
    coreDescription: "你的哈气像突然爆炸的低音炮——短促但震撼，低沉但不规则。",
    fullCopy: `🎆 **混沌低音炮 · 随机炸弹**\n\n你的哈气是一种"惊喜"——每次都不一样。\n\n响度大说明有冲击力，时间短说明出手快，频率低说明声音厚重，混沌度高说明完全没有规律。这四个属性组合在一起，你的哈气就像一颗随机炸弹——你永远不知道下一秒会炸出什么效果。\n\n有时候你的哈气像远处的闷雷，有时候像轮胎漏气，有时候像某人肚子咕咕叫。但无论哪种，都有一个共同点：**短促而震撼**。\n\n🎰 你的哈气就像老虎机——每次拉杆都是不同的结果，但总能给人惊喜（或惊吓）。`,
    hissPortrait: Object.freeze({
      loudness: 10,
      pitch: 4,
      endurance: 4,
      chaos: 10,
      stability: 2,
      burst: 10,
    }),
    knownCat: "半夜突然炸毛的布偶猫（随机爆发型）",
    socialTags: Object.freeze(["#随机炸弹", "#低音炮", "#惊喜", "#不可预测"]),
  }),

  HPFR: Object.freeze({
    code: "HPFR",
    name: "重锤手",
    title: "精准打击",
    dimensionCombo: "H（哈气型）+ P（脉冲型）+ F（低沉型）+ R（节奏型）",
    themeColor: "#708090（石板灰）",
    emoji: "🔨",
    rarityText: "★★★☆☆（较少见，约7%用户）",
    rarityRateText: "约7%用户",
    coreDescription: "你的哈气像锤子——短促、有力、方向明确。一锤定音，绝不废话。",
    fullCopy: `🔨 **重锤手 · 精准打击**\n\n你的哈气哲学是：能一声解决的事，绝不哈两声。\n\n响度大说明每一锤都有力，时间短说明出手果断，频率低说明声音厚重有力，节奏稳定说明每次出锤的角度和力度都一样。你就是哈气界的"效率派"——不浪费一丁点肺活量在无意义的延长上。\n\n你的哈气就像一个经验丰富的法官敲法槌：砰。一声就够了。不需要重复，不需要解释，不需要加强。砰完之后，全场安静。\n\n📐 你可能是一个：做事干脆利落的人、讨厌废话的人、以及"能发微信就不打电话"的人。`,
    hissPortrait: Object.freeze({
      loudness: 10,
      pitch: 4,
      endurance: 4,
      chaos: 2,
      stability: 10,
      burst: 10,
    }),
    knownCat: "被碰了一下就哈一声然后走开的猫（一锤定音型）",
    socialTags: Object.freeze(["#一锤定音", "#效率派", "#精准打击", "#不废话"]),
  }),

  SLTC: Object.freeze({
    code: "SLTC",
    name: "暗影刺客",
    title: "蓄力大师",
    dimensionCombo: "S（静默型）+ L（持久型）+ T（高音型）+ C（混沌型）",
    themeColor: "#2F4F4F（暗灰绿）",
    emoji: "🥷",
    rarityText: "★★★★☆（稀有，约6%用户）",
    rarityRateText: "约6%用户",
    coreDescription: "你平时安静得像不存在，但一旦开始哈气，就是持久+尖锐+混沌的三重暴击。",
    fullCopy: `🥷 **暗影刺客 · 蓄力大师**\n\n你是哈气界最危险的存在——因为你看起来最无害。\n\n你的整体响度不高，给人一种"这人不会哈气"的错觉。但一旦你开始，就会发现：持续时间超长、频率尖锐、而且完全没有规律。这三重属性叠加在一起，效果就像一个"蓄力后释放的大招"——前期越安静，后期越恐怖。\n\n你是猫界"装死然后突然暴起"的教科书案例。对方以为你是个软柿子，结果一捏——扎手了。\n\n🎭 你的哈气风格最适合：扮猪吃老虎、在PK中让对手轻敌然后翻盘、以及"你以为我很好欺负？"的场景。`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 10,
      endurance: 10,
      chaos: 10,
      stability: 2,
      burst: 7,
    }),
    knownCat: "被摸太久后突然暴起的猫（蓄力暴发型）",
    socialTags: Object.freeze(["#扮猪吃虎", "#蓄力大师", "#暗影刺客", "#别惹我"]),
  }),

  SLTR: Object.freeze({
    code: "SLTR",
    name: "蝉鸣者",
    title: "持续嗡鸣",
    dimensionCombo: "S（静默型）+ L（持久型）+ T（高音型）+ R（节奏型）",
    themeColor: "#228B22（森林绿）",
    emoji: "🦗",
    rarityText: "★★★☆☆（较少见，约7%用户）",
    rarityRateText: "约7%用户",
    coreDescription: "你的哈气像夏天的蝉鸣——声音不大但持续不断，尖锐但规律。",
    fullCopy: `🦗 **蝉鸣者 · 持续嗡鸣**\n\n你的哈气有一种特殊的杀伤力：精神污染。\n\n响度不大，不会让人感到威胁；频率偏高，有点刺耳；持续时间很长，非常长；而且节奏稳定，像节拍器一样精准。这四个属性组合在一起，效果就是——对方一开始不在意，三分钟后开始怀疑人生，五分钟后开始求你停下来。\n\n你的哈气就像一只在你耳边嗡嗡叫的蚊子——单个来看伤害不大，但持续不断地嗡嗡嗡嗡嗡，足以让人崩溃。\n\n🎧 你可能适合：做白噪音（反义的）、给不想理的人打电话、以及在图书馆里用气声说话。`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 10,
      endurance: 10,
      chaos: 2,
      stability: 10,
      burst: 4,
    }),
    knownCat: "对着窗外鸟持续低声哈气的猫（精神污染型）",
    socialTags: Object.freeze(["#蝉鸣", "#精神污染", "#持久嗡嗡", "#磨人"]),
  }),

  SLFC: Object.freeze({
    code: "SLFC",
    name: "潜流者",
    title: "暗流涌动",
    dimensionCombo: "S（静默型）+ L（持久型）+ F（低沉型）+ C（混沌型）",
    themeColor: "#191970（午夜蓝）",
    emoji: "🌊",
    rarityText: "★★★☆☆（较少见，约6%用户）",
    rarityRateText: "约6%用户",
    coreDescription: "你的哈气像深海暗流——表面平静，底下汹涌。对方说不清哪里不对，但就是莫名感到不安。",
    fullCopy: `🌊 **潜流者 · 暗流涌动**\n\n你的哈气是一种"说不清道不明"的存在。\n\n响度不大，不会引起注意；频率偏低，声音低沉；持续时间很长，一直在哈；而且频率变化不规则，像深海暗流一样不可预测。这四个属性组合在一起，效果就是——对方说不出你的哈气哪里可怕，但就是感到一种挥之不去的不安。\n\n你的哈气就像电影里的背景音乐——观众可能没有注意到它的存在，但如果没有它，整个氛围就完全不同。你的哈气在潜移默化中影响对方的情绪状态。\n\n🎬 你可能适合：做悬疑电影的音效设计、当心理咨询师（用低频声音影响来访者情绪）、以及"我不说话但你能感受到我的气场"的场景。`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 4,
      endurance: 10,
      chaos: 10,
      stability: 2,
      burst: 6,
    }),
    knownCat: "半夜盯着你看但不叫的猫（心理施压型）",
    socialTags: Object.freeze(["#暗流涌动", "#心理战", "#潜移默化", "#不安感"]),
  }),

  SLFR: Object.freeze({
    code: "SLFR",
    name: "念经猫",
    title: "低频念经",
    dimensionCombo: "S（静默型）+ L（持久型）+ F（低沉型）+ R（节奏型）",
    themeColor: "#DAA520（金色）",
    emoji: "🧘",
    rarityText: "★★★☆☆（较少见，约7%用户）",
    rarityRateText: "约7%用户",
    coreDescription: "你的哈气像寺庙念经——低沉、持续、有节奏。你不是在哈气，你是在做声波冥想。",
    fullCopy: `🧘 **念经猫 · 低频念经**\n\n你的哈气有一种"禅意"。\n\n响度低，像是在低声呢喃；频率低，声音厚重；持续时间长，像是在做某种仪式；而且节奏极其稳定，像节拍器一样精准。这四个属性组合在一起，你的哈气听起来就像——寺庙里的念经声。\n\n对方听着听着可能就睡着了（然后你趁机占领他的地盘）。你的哈气有一种催眠效果，不是因为无聊，而是因为那种低频、稳定、持续的声音会让人进入一种放松（或麻木）的状态。\n\n🧘 你可能是一个：说话慢条斯理的人、喜欢念叨的人、以及"我不是在抱怨我只是在陈述事实"的人。`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 4,
      endurance: 10,
      chaos: 2,
      stability: 10,
      burst: 4,
    }),
    knownCat: "蹲在窗台上对着空气低声咕噜的猫（冥想型）",
    socialTags: Object.freeze(["#念经", "#低频冥想", "#持久稳定", "#催眠效果"]),
  }),

  SPTC: Object.freeze({
    code: "SPTC",
    name: "惊雷猫",
    title: "猝不及防",
    dimensionCombo: "S（静默型）+ P（脉冲型）+ T（高音型）+ C（混沌型）",
    themeColor: "#FF1493（深粉色）",
    emoji: "🌩️",
    rarityText: "★★★☆☆（较少见，约7%用户）",
    rarityRateText: "约7%用户",
    coreDescription: "你99%的时间在沉默，剩下1%的时间在制造混乱。你的哈气像晴天霹雳。",
    fullCopy: `🌩️ **惊雷猫 · 猝不及防**\n\n你的哈气可以用两个字概括：惊吓。\n\n平时安静得像不存在（S型），哈气时间极短（P型），但一旦出手就是尖锐的（T型）+ 完全不可预测的（C型）暴击。这就像晴天霹雳——没人知道什么时候会来，来了就是震撼。\n\n你的哈气风格是"极致的反差"：沉默的时间越长，突然暴起的效果越震撼。就像一只安静蹲了两个小时的猫，突然对着路过的狗发出一声尖锐的嘶哈——狗都被吓跳了。\n\n🎭 你可能是一个：平时话不多但一开口就语出惊人的人、情绪稳定但偶尔爆发的人、以及"我平时脾气很好但你别踩我底线"的人。`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 10,
      endurance: 4,
      chaos: 10,
      stability: 2,
      burst: 10,
    }),
    knownCat: "被踩到尾巴后发出一声尖叫然后恢复安静的猫（惊雷型）",
    socialTags: Object.freeze(["#惊雷", "#猝不及防", "#反差", "#别踩底线"]),
  }),

  SPTR: Object.freeze({
    code: "SPTR",
    name: "蜜蜂猫",
    title: "精准嗡嗡",
    dimensionCombo: "S（静默型）+ P（脉冲型）+ T（高音型）+ R（节奏型）",
    themeColor: "#FFD700（蜜蜂黄）",
    emoji: "🐝",
    rarityText: "★★☆☆☆（较常见，约10%用户）",
    rarityRateText: "约10%用户",
    coreDescription: "你的哈气像蜜蜂——短促、尖锐、有节奏。嗡嗡嗡，虽然杀伤力不大，但烦人指数拉满。",
    fullCopy: `🐝 **蜜蜂猫 · 精准嗡嗡**\n\n你的哈气杀伤力可能不大，但烦人指数绝对拉满。\n\n响度不高（S型），不会造成实质性伤害；时间短（P型），每次就那么一下；频率偏高（T型），声音有点刺耳；但节奏很稳定（R型），嗡嗡嗡嗡嗡嗡，像一只在你耳边转圈的蜜蜂。\n\n单次哈气不可怕，可怕的是它会**反复出现**。就像蚊子——一巴掌拍不死，它还会回来。你的哈气就是这种"持续性骚扰"型，虽然每次都不致命，但累积效果足以让人崩溃。\n\n🐝 你可能是一个：喜欢碎碎念的人、擅长"精神攻击"的人、以及"我不是在吵架我只是在表达不满"的人。`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 10,
      endurance: 4,
      chaos: 2,
      stability: 10,
      burst: 8,
    }),
    knownCat: "对着飞虫短促有节奏地哈气的猫（精准嗡嗡型）",
    socialTags: Object.freeze(["#蜜蜂", "#嗡嗡嗡", "#精神攻击", "#烦人但可爱"]),
  }),

  SPFC: Object.freeze({
    code: "SPFC",
    name: "闷雷猫",
    title: "闷声发大狠",
    dimensionCombo: "S（静默型）+ P（脉冲型）+ F（低沉型）+ C（混沌型）",
    themeColor: "#483D8B（暗蓝色）",
    emoji: "🌑",
    rarityText: "★★★☆☆（较少见，约6%用户）",
    rarityRateText: "约6%用户",
    coreDescription: "你不常哈气，但每次都是低沉的一声闷响。像远处的雷声——不大，但你知道暴风雨要来了。",
    fullCopy: `🌑 **闷雷猫 · 闷声发大狠**\n\n你的哈气哲学是：少说话，说狠话。\n\n平时几乎不哈气（S型），每次哈气时间很短（P型），但声音低沉厚重（F型），而且每次的效果都不一样（C型）。这就像远处的闷雷——你听不清它在说什么，但你知道暴风雨要来了。\n\n你的哈气有一种"重量感"——虽然不大声，但每一声都像一块石头扔进水里，激起层层涟漪。对方可能不会被你的哈气吓到，但会感到一种"这个人不太好惹"的直觉。\n\n🌩️ 你可能是一个：平时沉默寡言但一开口就一针见血的人、不轻易发火但发火就很可怕的人、以及"我平时很好说话但你别试试看"的人。`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 4,
      endurance: 4,
      chaos: 10,
      stability: 2,
      burst: 10,
    }),
    knownCat: "被陌生人摸了一下后低声闷哈一声的猫（闷声发狠型）",
    socialTags: Object.freeze(["#闷雷", "#少说狠话", "#闷声发大狠", "#别惹"]),
  }),

  SPFR: Object.freeze({
    code: "SPFR",
    name: "弹珠猫",
    title: "弹珠落地",
    dimensionCombo: "S（静默型）+ P（脉冲型）+ F（低沉型）+ R（节奏型）",
    themeColor: "#87CEEB（天蓝色）",
    emoji: "💎",
    rarityText: "★★☆☆☆（较常见，约10%用户）",
    rarityRateText: "约10%用户",
    coreDescription: "你的哈气像弹珠落地——短促、低沉、清脆。每次就那么一声，不多不少。",
    fullCopy: `💎 **弹珠猫 · 弹珠落地**\n\n你的哈气有一种"极简主义"的美感。\n\n响度低（S型），像是在自言自语；时间短（P型），每次就那么一下；频率低（F型），声音低沉；节奏稳定（R型），每次都差不多。这四个属性组合在一起，你的哈气就像弹珠掉在地上的声音——"叮"的一声，清脆、低沉、简洁。\n\n你的哈气不多不少，每次就那么一声。不多废话，不拖泥带水。简洁是你的风格，效率是你的信仰。\n\n💎 你可能是一个：话少的人、做事干脆的人、以及"一个字就够了为什么要说一句"的人。`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 4,
      endurance: 4,
      chaos: 2,
      stability: 10,
      burst: 8,
    }),
    knownCat: "被吵醒后低声\"哈\"一下然后继续睡的猫（极简型）",
    socialTags: Object.freeze(["#极简", "#弹珠", "#简洁", "#不多废话"]),
  }),

  MEOOOW: Object.freeze({
    code: "MEOOOW",
    name: "喵星人",
    title: "叛徒猫",
    dimensionCombo: "",
    themeColor: "#FF69B4（热粉色）",
    emoji: "🐱",
    rarityText: "★★★★★（极稀有，约1%用户）",
    rarityRateText: "约1%用户",
    coreDescription: "等等……你录的不是哈气，是喵喵叫？在哈气模拟器里喵喵叫，就像在拳击场上比心。",
    fullCopy: `🐱 **喵星人 · 叛徒猫**\n\n🚨 警告：检测到非哈气音频！\n\n等等……你录的不是哈气，是喵喵叫？\n\n在一个专门测试哈气能力的模拟器里，你选择了喵喵叫。这就像在拳击场上比心、在吃辣比赛中点甜品、在辩论赛上说"你说得对"。\n\n你的行为可以被解读为：\n- 🤝 你是一个和平主义者，拒绝参与哈气这种攻击性行为\n- 😏 你在故意挑衅这个系统\n- 🥺 你真的不知道什么是哈气\n- 🎭 你在用"喵喵叫"进行更高维度的哈气——精神哈气\n\n无论哪种解读，你都成功触发了隐藏人格"喵星人"。恭喜你，叛徒猫！\n\n🏅 **特殊成就解锁：** "叛徒猫"徽章`,
    hissPortrait: Object.freeze({
      loudness: 6,
      pitch: 2,
      endurance: 6,
      chaos: 6,
      stability: 8,
      burst: 4,
    }),
    knownCat: "",
    socialTags: Object.freeze([]),
  }),

  SILENT: Object.freeze({
    code: "SILENT",
    name: "虚无猫",
    title: "空气哈气大师",
    dimensionCombo: "",
    themeColor: "#E0E0E0（浅灰色）",
    emoji: "🫧",
    rarityText: "★★★★★（极稀有，约1%用户）",
    rarityRateText: "约1%用户",
    coreDescription: "你按下了录制键，然后……什么都没发生。最高的哈气境界，就是不需要哈气。",
    fullCopy: `🫧 **虚无猫 · 空气哈气大师**\n\n你按下了录制键，然后……什么都没发生。\n\n没有声音，没有哈气，只有空气在颤抖。系统检测到你的音频响度低于20dB（基本上就是安静的房间），或者你录制了不到0.3秒就按了停止。\n\n这可以被解读为：\n- 🧘 你已经达到了哈气的最高境界——"无声胜有声"。真正的哈气大师不需要发出声音，他的气场本身就是一种哈气。\n- 😅 你不小心按到了录制按钮\n- 🤔 你在测试这个系统是否能检测到静音\n- 🎨 你在进行一种前卫的行为艺术——"沉默的哈气"\n\n无论哪种解读，你都成功触发了隐藏人格"虚无猫"。恭喜你，空气哈气大师！\n\n🏅 **特殊成就解锁：** "空气大师"徽章`,
    hissPortrait: Object.freeze({
      loudness: 0,
      pitch: 0,
      endurance: 0,
      chaos: 0,
      stability: 0,
      burst: 0,
    }),
    knownCat: "",
    socialTags: Object.freeze([]),
  }),
});

export function getPersonalityProfile(code) {
  const profile = PERSONALITY_CATALOG[code];
  if (!profile) {
    throw new UnknownPersonalityCodeError(code);
  }
  return profile;
}

