name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: node --version
      - run: npm test
      - run: npm run test:report
      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: reports/unit-test-report.txt

